export const USER_ACTION_TYPES = {
  USER_REGISTER_START: "user/USER_REGISTER_START",
  USER_REGISTER_SUCCESS: "user/USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "user/USER_REGISTER_FAILURE",
  USER_SIGNIN_START: "user/USER_SIGNIN_START",
  USER_SIGNIN_SUCCESS: "user/USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILURE: "user/USER_SIGNIN_FAILURE",
  USER_SIGNOUT_START: "USER_SIGNOUT_START",
  USER_SIGNOUT_SUCCESS: "USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAILURE: "USER_SIGNOUT_FAILURE",
};
